version: '2'
services:
  nginx:
    build: /home/amirreza/nginx/
    links: 
      - app
    ports:
      - "80:80"
      - "443:443"
  app:
    build: .
    links:
      - mysql
    ports:
      - "8081:80"

  mysql:
    image: "percona:8.0"
    environment:
      - MYSQL_DATABASE=hamgoonDb
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3306:3306"
    expose:
      - '3306' 
    volumes:
      - "/mysql_data:/var/lib/mysql"
  
