// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using HamgoonAPIV1.Services.RocketChat;
//
//    var rocketLoginResponse = RocketLoginResponse.FromJson(jsonString);

namespace HamgoonAPIV1.Services.RocketChat
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class RocketLoginResponse
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("authToken")]
        public string AuthToken { get; set; }

        [JsonProperty("userId")]
        public string UserId { get; set; }

        [JsonProperty("me")]
        public Me Me { get; set; }
    }

    public partial class Me
    {
        [JsonProperty("_id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("emails")]
        public Email[] Emails { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("statusConnection")]
        public string StatusConnection { get; set; }

        [JsonProperty("username")]
        public string Username { get; set; }

        [JsonProperty("utcOffset")]
        public long UtcOffset { get; set; }

        [JsonProperty("active")]
        public bool Active { get; set; }

        [JsonProperty("roles")]
        public string[] Roles { get; set; }

        [JsonProperty("settings")]
        public Settings Settings { get; set; }

        [JsonProperty("avatarUrl")]
        public Uri AvatarUrl { get; set; }
    }

    public partial class Email
    {
        [JsonProperty("address")]
        public string Address { get; set; }

        [JsonProperty("verified")]
        public bool Verified { get; set; }
    }

    public partial class Settings
    {
        [JsonProperty("preferences")]
        public Preferences Preferences { get; set; }
    }

    public partial class Preferences
    {
    }

    public partial class RocketLoginResponse
    {
        public static RocketLoginResponse FromJson(string json) => JsonConvert.DeserializeObject<RocketLoginResponse>(json, HamgoonAPIV1.Services.RocketChat.Converter.Settings);
    }

    public static class RegisterSerialize
    {
        public static string ToJson(this RocketLoginResponse self) => JsonConvert.SerializeObject(self, HamgoonAPIV1.Services.RocketChat.Converter.Settings);
    }

    internal static class RegisterConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
