version: '3'
services: 
  app: 
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: "percona:8.0"
    ports: 
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: "ShIn3Ony0uCRazYDi@m0nd"
        MYSQL_DATABASE: "hamgounDb"