version: '3'
services:
  app:
    build: .
    links:
      - mysql
    ports:
      - "80:80"

  mysql:
    image: "percona:8.0"
    ports:
      - "3306:3306"
    volumes:
      - "/mysql_data:/var/lib/mysql"
  